/*********************************************/
/********************************************/
/*********	AUTHOR: Amr Tawakol ************/
/*********	LAYER: MCAL		    ***********/
/*********	MODULE: DIO		    **********/
/*********	Version: 1.00		*********/
/*********	Date: 2/8/2023	    ********/



#ifndef _MDIO_COFIG_H_
#define _MDIO_CONFIG_H_


#define PORTA_PIN7_DIR	OUTPUT
#define PORTA_PIN6_DIR	OUTPUT
#define PORTA_PIN5_DIR	OUTPUT
#define PORTA_PIN4_DIR	OUTPUT
#define PORTA_PIN3_DIR	OUTPUT
#define PORTA_PIN2_DIR	OUTPUT
#define PORTA_PIN1_DIR	OUTPUT
#define PORTA_PIN0_DIR	OUTPUT

#define PORTB_PIN7_DIR	INPUT
#define PORTB_PIN6_DIR	OUTPUT
#define PORTB_PIN5_DIR	INPUT
#define PORTB_PIN4_DIR	OUTPUT
#define PORTB_PIN3_DIR	OUTPUT
#define PORTB_PIN2_DIR	OUTPUT
#define PORTB_PIN1_DIR	OUTPUT
#define PORTB_PIN0_DIR	OUTPUT

#define PORTC_PIN7_DIR	OUTPUT
#define PORTC_PIN6_DIR	OUTPUT
#define PORTC_PIN5_DIR	OUTPUT
#define PORTC_PIN4_DIR	OUTPUT
#define PORTC_PIN3_DIR	OUTPUT
#define PORTC_PIN2_DIR	OUTPUT
#define PORTC_PIN1_DIR	OUTPUT
#define PORTC_PIN0_DIR	OUTPUT

#define PORTD_PIN7_DIR	OUTPUT
#define PORTD_PIN6_DIR	OUTPUT
#define PORTD_PIN5_DIR	OUTPUT
#define PORTD_PIN4_DIR	OUTPUT
#define PORTD_PIN3_DIR	OUTPUT
#define PORTD_PIN2_DIR	OUTPUT
#define PORTD_PIN1_DIR	OUTPUT
#define PORTD_PIN0_DIR	OUTPUT

#define PORTA_PIN7_VALUE	LOW
#define PORTA_PIN6_VALUE	LOW
#define PORTA_PIN5_VALUE	LOW
#define PORTA_PIN4_VALUE	LOW
#define PORTA_PIN3_VALUE	LOW
#define PORTA_PIN2_VALUE	LOW
#define PORTA_PIN1_VALUE	LOW
#define PORTA_PIN0_VALUE	LOW

#define PORTB_PIN7_VALUE	LOW
#define PORTB_PIN6_VALUE	LOW
#define PORTB_PIN5_VALUE	LOW
#define PORTB_PIN4_VALUE	LOW
#define PORTB_PIN3_VALUE	LOW
#define PORTB_PIN2_VALUE	LOW
#define PORTB_PIN1_VALUE	LOW
#define PORTB_PIN0_VALUE	LOW

#define PORTC_PIN7_VALUE	LOW
#define PORTC_PIN6_VALUE	LOW
#define PORTC_PIN5_VALUE	LOW
#define PORTC_PIN4_VALUE	LOW
#define PORTC_PIN3_VALUE	LOW
#define PORTC_PIN2_VALUE	LOW
#define PORTC_PIN1_VALUE	LOW
#define PORTC_PIN0_VALUE	LOW

#define PORTD_PIN7_VALUE	LOW
#define PORTD_PIN6_VALUE	LOW
#define PORTD_PIN5_VALUE	LOW
#define PORTD_PIN4_VALUE	LOW
#define PORTD_PIN3_VALUE	LOW
#define PORTD_PIN2_VALUE	LOW
#define PORTD_PIN1_VALUE	LOW
#define PORTD_PIN0_VALUE	LOW



#endif
